### ISSUE TITLE
Login broken

### ISSUE THREAD

**Issue by MTrab** [EishaV/Desktop-App#10]
FYI - the Landxcape login is broken as of now.
Haven't figured out what have changed yet.

`404 Client Error: Not Found for url: https://api.landxcape-services.com/api/v2/oauth/token`

Logged it at my own tracker as well: https://github.com/MTrab/pyworxcloud/issues/81

**Comment by MTrab** [comment]
@EishaV 
This is the same issue for all the makes. None are working.
I expect to have this sorted for pyworxcloud sometime next week, then I'll share the solution. Please do the same if you find the changes before me

**Comment by michapr** [comment]
Hi, have you a chance to update the App? 
I have seen that it was fixed for HA (https://github.com/MTrab/landroid_cloud/pull/266) - so I hope you know what to change in code ;)

THANKS!
Michael

**Comment by michapr** [comment]
Fixed in version 0.028
Download via other link...
see https://www.roboter-forum.com/threads/entwicklungsprojekt-worx-landroid-kress-mission-desktop-app.22795/
