### ISSUE TITLE
localisation issue

### ISSUE THREAD

**Issue by OhSoGood** [EishaV/Desktop-App#2]
Hi again :)
You app is excellent, but it has 2 issues with localisation:
- Have you noticed that, by using a simple translation, you got into positioning issues? Depending on the language, the same group of words may take more or less space. And so several labels or buttons get truncated. You should have used maybe the built-in localization mechasnim of .NET...
- A few texts are hard-coded in the winform designer (ex: Rundfahrt, Beschreibung)

**Comment by EishaV** [comment]
The translation I built later based on the XML of Android. This way, users can translate the texts above all. With resources this is rather difficult.
If you give me the XML in French, then I can adjust the appropriate places (enlarge ;-).
The places which are still hard-coded we can correct successively.
Currently I am working on the Xamarin app.

**Comment by EishaV** [comment]
Changes for V0.0.25

Property AutoSize = True (GrowOnly) for all buttons.

Load text for button "zone training" from xml.
<string name="da_zone_train">&amp;Rundfahrt</string>
  
New translations for tab Plugin
  <string name="da_plug">Plugin</string>
  <string name="da_plug_code">Skript</string>
  <string name="da_plug_desc">Beschreibung</string>

**Comment by OhSoGood** [comment]
Cool. Thank you. I think we can close the issue.
