### ISSUE TITLE
Question on multi-zone

### ISSUE THREAD

**Issue by OhSoGood** [EishaV/Desktop-App#3]
Hi
Could you explain how the definition of multi-zone works in your app?
- Must there always be 4 zones?
- If a zone is unused, what should be its distance? 0? -1 ?
- To what do the numbers 0 to 9 correspond for multi-zone? Is it a kind of scheduling?
Thank you!

**Comment by EishaV** [comment]
Must there always be 4 zones?
No, it's less.
They would have to be created from the front, so 1, 2, ...

If a zone is unused, what should be its distance? 0? -1 ?
An unused zone (behind the used ones) is given as 0 meters.
Unfortunately, a start, when using zones, out of the charging station is not possible with 0.

To what do the numbers 0 to 9 correspond for multi-zone? Is it a child of scheduling?
You can specify the starting points for 10 exits (mzv 0-9). There you enter the index of the multizone (mz 0-3). The last starting point shows the mower over lz in the status.

(translate by google ;-)

**Comment by OhSoGood** [comment]
Thank you for the answer! Could you give some example for the last question? I'm not sure to understand. 
And thanks again for your app, I no more use the official app on android... Actually, I think I'll implement it as a website, so that anybody in the family can use it without having to install anything.
Regards

**Comment by EishaV** [comment]
mz[] = { 5, 10, 20, 30 }
mzv[] = { 0,1,2,3,0,3,0,2,3,0 }

0 05m 40%
1 10m 10%
2 20m 20%
3 30m 30%

First exit at 5m, second at 10m, ...
lz show the index in mzv, so you can dertmine the start point for the next exit.


The assemblages logic and store from the Xamarin project are dotnet core. These would also run in ASP Net.
I do not know how you would implement the Mqtts communication in the browser.
