### ISSUE TITLE
show current zone

### ISSUE THREAD

**Issue by michapr** [EishaV/Desktop-App#5]
Hi,

thank you for the great application!

Is it possible to show anywhere the current Zone - where the Landroid is just working?
In Android App will be displayed current zone - so I hope anywhere this information could be ;)

Yould be nice to write it into the status (for export) ;)

BTW: is anywhere described what mean all the short values like "lk", "lz", .... ?

Thanks!
Michael

**Comment by EishaV** [comment]
Hi,

on register "Status" you will see "SPx" the last start point on mowing or the next start point from base.

It is exported, mean CSV. The value d.LastZone.

See MqttJson.cs, its explain all values that are know.

You know: https://www.roboter-forum.com/index.php?thread/22795-entwicklungsprojekt-worx-landroid-kress-mission-desktop-app/

Bye, EishaV
