### ISSUE TITLE
login expires?

### ISSUE THREAD

**Issue by pa2hbn** [EishaV/Desktop-App#9]
using version V0.0.27b.
Just after loading the Desktop-App, It is always needed tot log in on the first tab to be able to see Activities via the refresh on the activities tab.
If not active for some time, the refresh on the activities tab does not work anymore, I get an error:
The remote server returned an error: (401) Unautorized.
Seems that I am not logged in anymore, but there is no way to login on the User tab, the login button is grayed-out afther the first login.
Is there a way to re-login? or maybe it is possible to keep the App logged in
![worx-desk-app-error](https://user-images.githubusercontent.com/36407003/171446249-82018291-2013-4d38-8c20-3763d61a2799.PNG)
,

**Comment by EishaV** [comment]
Positec changed the access.
